const cities = [
  { woeid: '2306179', cname: '台北' },
  { woeid: '2306180', cname: '高雄' },
  { woeid: '2306181', cname: '台中' },
  { woeid: '2306182', cname: '台南' },
  { woeid: '2306183', cname: '彰化' },
  { woeid: '2306184', cname: '桃園' },
  { woeid: '2306185', cname: '新竹' },
  { woeid: '2306187', cname: '花蓮' },
  { woeid: '2306188', cname: '基隆' },
  { woeid: '2306189', cname: '屏東' },
  { woeid: '2306190', cname: '台東' },
  { woeid: '2306198', cname: '宜蘭' },
  { woeid: '2306204', cname: '南投' },
  { woeid: '2306206', cname: '嘉義' },
  { woeid: '2306211', cname: '新北市' },
  { woeid: '2306212', cname: '雲林' },
  { woeid: '2306229', cname: '苗栗' },
];

const weather_icon = {
  "0": ["wi-day-cloudy", "多雲"],
  "1": ["wi-day-cloudy", "多雲"],
  "2": ["wi-day-rain", "雨天"],
  "3": ["wi-day-thunderstorm", "雷雨"],
  "4": ["wi-day-thunderstorm", "雷雨"],
  "5": ["wi-day-rain", "雨天"],
  "6": ["wi-day-rain", "雨天"],
  "7": ["wi-day-rain", "雨天"],
  "8": ["wi-day-rain", "雨天"],
  "9": ["wi-day-rain", "雨天"],
  "10": ["wi-day-rain", "雨天"],
  "11": ["wi-day-rain", "雨天"],
  "12": ["wi-day-rain", "雨天"],
  "13": ["wi-day-rain", "雨天"],
  "14": ["wi-day-rain", "雨天"],
  "15": ["wi-day-rain", "雨天"],
  "16": ["wi-day-rain", "雨天"],
  "17": ["wi-day-rain", "雨天"],
  "18": ["wi-day-rain", "雨天"],
  "19": ["wi-day-cloudy", "多雲"],
  "20": ["wi-day-cloudy", "多雲"],
  "21": ["wi-day-cloudy", "多雲"],
  "22": ["wi-day-cloudy", "多雲"],
  "23": ["wi-day-cloudy", "多雲"],
  "24": ["wi-day-cloudy", "多雲"],
  "25": ["wi-day-cloudy", "多雲"],
  "26": ["wi-day-cloudy", "多雲"],
  "27": ["wi-day-cloudy", "多雲"],
  "28": ["wi-day-cloudy", "多雲"],
  "29": ["wi-day-cloudy", "多雲"],
  "30": ["wi-day-cloudy", "多雲"],
  "31": ["wi-day-sunny", "晴天"],
  "32": ["wi-day-sunny", "晴天"],
  "33": ["wi-day-sunny", "晴天"],
  "34": ["wi-day-sunny", "晴天"],
  "35": ["wi-day-cloudy", "多雲"],
  "36": ["wi-day-sunny", "晴天"],
  "37": ["wi-day-thunderstorm", "雷雨"],
  "38": ["wi-day-cloudy", "多雲"],
  "39": ["wi-day-cloudy", "多雲"],
  "40": ["wi-day-cloudy", "多雲"],
  "41": ["wi-day-rain", "雨天"],
  "42": ["wi-day-rain", "雨天"],
  "43": ["wi-day-rain", "雨天"],
  "44": ["wi-day-cloudy", "多雲"],
  "45": ["wi-day-cloudy", "多雲"],
  "46": ["wi-day-rain", "雨天"],
  "47": ["wi-day-cloudy", "多雲"],
  "3200": "資料錯誤"
}